// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWmojKv3WmiXGxE8mZz6wTGUdjFZsfRMo',
    appId: '1:738586606528:web:2ca509de0f33b5b6cee625',
    messagingSenderId: '738586606528',
    projectId: 'bus-live-tracker-1fd6b',
    authDomain: 'bus-live-tracker-1fd6b.firebaseapp.com',
    databaseURL: 'https://bus-live-tracker-1fd6b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bus-live-tracker-1fd6b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLnohOIvDshz6IfUs55YN-_mKSKCl3nrk',
    appId: '1:738586606528:android:5f7ee779675a758bcee625',
    messagingSenderId: '738586606528',
    projectId: 'bus-live-tracker-1fd6b',
    databaseURL: 'https://bus-live-tracker-1fd6b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bus-live-tracker-1fd6b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH4nHRW8NFKFR9R99_4bjWIK_jIwaqMIw',
    appId: '1:738586606528:ios:34b5c998d3ef045ecee625',
    messagingSenderId: '738586606528',
    projectId: 'bus-live-tracker-1fd6b',
    databaseURL: 'https://bus-live-tracker-1fd6b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bus-live-tracker-1fd6b.firebasestorage.app',
    iosBundleId: 'com.example.trackMyBus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAH4nHRW8NFKFR9R99_4bjWIK_jIwaqMIw',
    appId: '1:738586606528:ios:34b5c998d3ef045ecee625',
    messagingSenderId: '738586606528',
    projectId: 'bus-live-tracker-1fd6b',
    databaseURL: 'https://bus-live-tracker-1fd6b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bus-live-tracker-1fd6b.firebasestorage.app',
    iosBundleId: 'com.example.trackMyBus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjBDeDicAwQdud3hVoXdJxzNTJgf9Bjlw',
    appId: '1:738586606528:web:9c925e3ae346348ecee625',
    messagingSenderId: '738586606528',
    projectId: 'bus-live-tracker-1fd6b',
    authDomain: 'bus-live-tracker-1fd6b.firebaseapp.com',
    databaseURL: 'https://bus-live-tracker-1fd6b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bus-live-tracker-1fd6b.firebasestorage.app',
  );

}